[package]
name = "amazon_qldb_shell"
version = "0.1.0"
authors = ["Marc Bowes <bowes@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amazon-qldb-driver = { git = "https://github.com/awslabs/amazon-qldb-driver-rust", branch = "main" }
rusoto_core = "0.46.0"
rusoto_qldb_session = "0.46.0"
rustyline = "8.0.0"
dirs = "3.0.1"
log = "0.4.14"
fern = "0.6.0"
structopt = "0.3.21"
ion-c-sys = "0.4.4"
chrono = "0.4.19"
async-trait = "0.1.48"
rustyline-derive = "0.4.0"
itertools = "0.10.0"
thiserror = "1.0.24"
anyhow = "1.0.39"
tokio = "1.4.0"
toml = "0.5.8"
serde = "1.0.125"
pest = "2.1.3"
pest_derive = "2.1.0"
tracing = { version = "0.1.25", features = ["log"] }

[dev-dependencies]
tempdir = "0.3"

[[bin]]
name = "qldb"
path = "src/main.rs"
